export default trails = 
	[
		{
            city: "Boulder",
            name: "Ber Peak Trail",
            directions:"None Listed",
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/11209020/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7.7 mile loop",
            description:"Features beautiful wild flowers and is rated as difficult. The trail is primarily used for hiking, walking, nature trips, and birding and is best used from March until October. Dogs are also able to use this trail but must be kept on leash."
        },
        {
            city: "Boulder",
            name: "First and Second Flatiron Hike",
            directions:"Directions from Highway 36: Take the Baseline Road exit and travel west toward the mountains. Follow Baseline Road 1.5 miles passed the entrance for Chautaugua Park to the Gregory Canyon Trailhead. Turn left into the parking lot on a dirt road. A parking fee is charged at this trailhead for vehicles not registered in Boulder County or not displaying a Boulder Resident Permit. Permits can be obtained at the trailhead or at the Chautaugua Park Rangers Cottage.",
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/11068245/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"2.7 mile loop ",
            description:"Features beautiful wild flowers and is rated as difficult. The trail is primarily used for hiking, walking, trail running, and rock climbing and is best used from March until September. Dogs are also able to use this trail."
        },
    {       city: "Boulder",
            name: "Mallory Cave",
            directions:"In south Boulder, head west on Table Mesa Dr all the way to the NCAR parking lot. Broadway and US 36 cross this road.",
            lat: -105.289398,
            lon: 39.974117,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/18767132/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"2.7 miles",
            description:"This hike starts at the NCAR parking lot. Head west to the Mesa trail and cross it by the information sign. There are lots of offshoot trails, be sure to follow the signs to the final 100 ft rock climb. If there is no ice or snow proceed up to the cave."
    },
    {       city: "Boulder",
            name: "Mesa Trail",
            directions:"From Denver, north on 93, left on 170 just south of Boulder.  A mile or two to parking on the left.",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11084601/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7.5 miles",
            description:"Features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is best used from July until July. Dogs and horses are also able to use this trail."
    },
    {       city: "Boulder",
            name: "Mount Sanitas Trail",
            directions:"Directions from Broadway: Traveling north passed the University turn left on to Mapleton Avenue. The trailhead lies approximately seven blocks west of Broadway. While parts of this hike are dog friendly, dogs are not allowed on Lions lair section of the trail.",
            lat: 40.019984,
            lon: 105.295178,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11581533/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"3.3 mile loop",
            description:" Features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is best used from March until October. Dogs are also able to use this trail but must be kept on leash."
    },
    {       city: "Boulder",
            name: "Walker Ranch Loop",
            directions:"None Listed",
            lat: 39.955835,
            lon: 105.094576,
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/19096555/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7.5 mile loop",
            description:"Walker Ranch is a fantastic loop, that can be taken both clockwise and counter. Going counter clockwise starts you off on a fantastic downhill, just be careful for walkers & dogs. Once at the bottom, you will start a moderate but tiring climb that eventually opens up at the top into an area with a parking lot, which is where the real fun starts! From this point you will experience what some would argue is 2 miles of the best downhill you will ever ride. This is followed by a short portage down some very steep steps, followed by another moderate climb back to the trail head. If you still need more, just turn around and start again, going the opposite direction, because by now you know the climb you did through the forest at the end of the ride back is gonna be some great downhill."
    },
    {
            city: "Boulder",
            name: "Royal Arch Trail",
            directions:"Directions from Highway 36: Chautauqua Trail Access: Take the Baseline Road exit and travel west toward the mountains. Follow Baseline Road nearly 1.5 miles to the entrance for Chautauqua Park. Turn left into the park. Parking is free at this trailhead.",
            lat: 39.9819444,
            lon: -105.2913889,
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/18993890/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"3.4 mile loop",
            description:"Start on Chautauqua trail by the ranger station. After crossing a grassy meadow you enter a pine forest. Start paying attention to signs for Royal Arch as a number of other trails branch off. You know you're going the right way when you get to the flagstone staircase."
    },
    {
            city: "Breckinridge",
            name: "Bald Mountain Trail",
            directions: "From Boulder Head west on Mapleton.  Once it turns into Sunshine Canyon Drive (County Road 52), go about 4.5 miles until you get to the Bald Mountain Scenic Area on the south side of the road.",
            lat: 40.04761,
            lon: -105.34131,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11073399/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"8.2 miles",
            description: "The trail is primarily used for hiking, cross country skiing, and snowshoeing and is best used from June until October."
    },
    {
            city: "Brighton",
            name: "Barr Lake Trail",
            directions: "None Listed",
            description: "The trail offers a number of activity options and is accessible year-round. Horses are also able to use this trail. $7 Parking Fee for the day",
            miles:"9 mile loop",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/13805293/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",

    },
    {
            city: "Brighton",
            name: "South Fork Preble Creek",
            directions: "None Listed",
            description: "A simple trail in the North Creek Farms Subdivision. The trail is primarily used for hiking and is accessible year-round. Dogs are also able to use this trail but must be kept on leash.",
            miles:"1.7 miles",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/11197707/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",

    },
    {
            city: "Clark",
            name: "Tombstone Nature Trail",
            directions: "Go west two miles on U.S. 40 to County Road 129 (also called Elk River Road). Turn north and drive 25 miles. The Visitor Center is on the left-hand side of the road. You can't miss us!",
            difficulty:"Easy",
            miles:" 1 mile loop",
            picture:"https://www.alltrails.com/api/alltrails/photos/11103077/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description: "Features a lake and is good for all skill levels. The trail is primarily used for hiking, walking, nature trips, and birding and is best used from March until October.",
     
    },
    {
            city: "Clark",
            name: "Willow Creek Trail",
            directions: "None Listed",
            difficulty: "Moderate",
            miles: "8.2 miles",
            picture: "https://www.alltrails.com/api/alltrails/photos/11576251/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description: "Willow Creek Trail is a 8.2 mile lightly trafficked out and back trail located near Clark, Colorado that features a lake and is rated as moderate. The trail is primarily used for hiking and camping and is best used from May until October. Dogs are also able to use this trail.",
    },
    {       city: "Colorado Springs",
            name: "Cap'n Jacks Trail to Jones Park and Bear Creek Trail",
            directions:"Directions: Exit I-25 at exit 140. Go south on Tejon and bear right onto Cheyenne Blvd. This joins W. Cheyenne Canyon Rd about 50 yards from the Starsmore Discovery Center. Turn right onto North Cheyenne Canyon Rd and drive approximately 1.5 miles to the trailhead.",
            lat: 38.7908,
            lon: 104.8761,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/13766988/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"13.6 miles",
            description:"Old Gold Camp Road leads to many of the hiking treasures of Colorado Springs. One of my favorites is the trek from High Rd via Cap'n Jacks trail, over the ridge between Mt Kineo and Mt Buckhorn, down through Jones Park, and up the Bear Creek run to the meadow below Tuckaway Mtn. Total elevation gain for this journey is about 2400 ft over a distance (round trip) of about 10 miles. This may seem like it's out in the middle of nowhere, but when you come across an old water pipeline, a mine shaft, Loud's Cabin, and a century's old U.S. Geological Survey marker, you realize that real people tried living and working out here at one time. Jones Park, in the middle of this hike, was designed to be the location of a hotel and restaurant for those traveling up the road to Pike's Peak."
    },
    {
            city: "Colorado Springs",
            name: "The Chutes",
            directions: "From I-25, exit at Hwy 24 West.  Go about a mile and turn left onto 21st Street.  Go about 3 miles on 21st to W Cheyenne Blvd.  Turn right.  Go about half a mile and turn right onto Ridgeway Ave.  Stratton Open Space and parking lot is on the right.",
            lat: 38.79517,
            lon: -104.85853,
            difficulty:"Moderate",
            miles:"4.1 mile loop",
            picture:"https://www.alltrails.com/api/alltrails/photos/11101806/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description: "The trail offers a number of activity options and is accessible year-round. Dogs are also able to use this trail but must be kept on leash.",

    },
    {       city: "Colorado Springs",
            name:"Coyote Gulch Trail and Creekbottom Loop",
            directions:"None Listed",
            lat: 38.8223,
            long: 104.8620,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/10660326/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.4 mile loop",
            description:"Offers the chance to see wildlife and is good for all skill levels. The trail is primarily used for hiking, trail running, nature trips, and birding and is best used from May until August."
    },
    {       city: "Colorado Springs",
            name: "Helen Hunt Falls Trail",
            directions:"Take the Nevada Exit off of I-25 on the South side of Colorado Springs.  Follow Nevada south a few blocks to Cheyenne Blvd.  Turn West on Cheyenne Blvd.  Continue on this road until you reach a fork in the road with a sign for Helen Hunt falls to the right and Seven Falls to the left.  This will take you into Cheyenne Canyon.  Follow this curvy road until you get to the vistors station at a large switchback in the road.  Park here.",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/11273959/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"0.1 miles",
            description:"This is well populated hiking location with a visitor's center open in the summer months. You can view the falls from the road so it's easy to bring children or those who may have trouble hiking. There is a  steep hiking trail wraps along the creek to a look out point above the falls. The trail is primarily used for hiking, walking, nature trips, and birding and is best used from March until October. Dogs are also able to use this trail but must be kept on leash."
    },
    {       city: "Colorado Springs",
            name: "Mount Cutler Trail",
            directions:"Directions: Exit I-25 at exit 140. Go south on Tejon and bear right onto Cheyenne Blvd. This joins W. Cheyenne Canyon Rd about 50 yards from the Starsmore Discovery Center. Turn right onto North Cheyenne Canyon Rd and drive approximately 1.5 miles to the trailhead.",
            lat: 38.7908,
            lon: 104.8761,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/19231428/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.8 miles",
            description:"Here is a leisurely family hike you can do in a morning or afternoon. The hike is only 2 miles in length. Mt Cutler - named after Henry Cutler, one of General Palmer's friends and a supporter of Colorado College - rises above Cheyenne Creek about half way up the Cheyenne Canyon, on the south side. The trailhead is well marked and has ample parking. Spectacular views are available from the summits. I'd recommend early morning or late afternoon for the best lighting."
    },
    {       city: "Colorado Springs",
            name: "Mount Muscoco Trail",
            directions:"None Listed",
            lat: 38.7908,
            lon: 104.8761,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/13746229/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"3.7 miles",
            description:"The Mount Muscoco trailhead is the same as Mount Cutler trailhead and the trails are the same for about a half mile until they split to go their separate ways. The trail is 2.1 miles one-way with about 1,300 feet elevation gain. Wonderful views at the top."
    },
    {       city: "Colorado Springs",
            name: "Palmer Trail (Section 16)",
            directions: "None Listed",
            lat: 38.877232,
            lon: -104.774529,
            difficulty: "Moderate",
            picture: "https://www.alltrails.com/api/alltrails/photos/10408806/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"5.2 miles",
            description:"Features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is best used from March until November. Dogs and horses are also able to use this trail."
    },
    {       city: "Colorado Springs",
            name: "Quail Lake Trail",
            directions:"None Listed",
            lat: 38.7865,
            lon: 104.8063,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/10581017/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.1 miles",
            description:"The trail is good for all skill levels and primarily used for hiking and walking. Dogs are also able to use this trail but must be kept on leash."
    },
    {       city: "Colorado Springs",
            name: "Red Rock Canyon Trails",
            directions:"This trailhead is located just off of Highway 24 on the West side of Colorado Springs.  Turn south off of 24 onto Ridge Road.  The very first left after this turn will take you through a gate and into the parking lot for the trailhead.",
            lat: 38.8784,
            lon: 104.8698,
            difficulty:"Easy, Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/12982480/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"5.3 mile loop",
            description:"The land now included in the 'Open Space' has been in use for at least 9,000 years, where because of its proximity to Fountain Creek early American settlers made their homes. In the more recent past, the Dakota Sandstone layer was used to quarry building materials, and portions of the park received trainloads of gold ore from the Cripple Creek mines to be refined. Since 2003 the city of Colorado Springs has developed this property into one of its premier parks, containing nearly 10 miles of connected trails suitable for hikers, bikers, and horse back riders (some trails are restricted to only one type of adventurer). The park is open year round from dawn to dusk, and with such varied terrain, you'll never tire of visiting and creating new ways of enjoying this delightful topography."
    },
    {
            city: "Colorado Springs",
            name: "Seven Bridges Trail",
            directions: "Take West Cheyenne road or West Cheyenne boulevard to the Starsmore Discovery Center entrance and then drive up toward Helen Hunt Falls.  Once you pass the HH Falls visitor center keep going up until you get to the parking area.  From there walk the Gold Camp road, past the gate, .7 miles until you hit the Seven Bridges trailhead.",
            lat: 38.72896,
            lon: -104.90892,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11307716/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"3.8 miles",
            description:"The trail is primarily used for hiking, walking, and trail running and is best used from March until November. Dogs are also able to use this trail but must be kept on leash. Seven cascading waterfalls with a total of 224 steps."
 
    },
    {       city: "Colorado Springs",
            name: "Silver Cascade Falls Trail",
            directions:"Take the Nevada Exit off of I-25 on the South side of Colorado Springs.  Follow Nevada south a few blocks to Cheyenne Blvd.  Turn West on Cheyenne Blvd.  Continue on this road until you reach a fork in the road with a sign for Helen Hunt falls to the right and Seven Falls to the left.  This will take you into Cheyenne Canyon.  Follow this curvy road until you get to the vistors station at a large switchback in the road.  Park here.",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/10274087/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"0.7 miles",
            description:"Short hike in Cheyenne Canyon to some interesting falls. Take the trail that leads up above Helen Hunt Falls.  Continue up the hillside on this trail as it does a couple of switchbacks.  Cross a small bridge near the end and head out to the overlook surrounded by a rock wall.  These falls are beautiful when flowing strong, but dry up quickly to a trickle. Dogs are also able to use this trail but must be kept on leash."
    },
    {       city: "Colorado Springs",
            name: "St. Mary's Falls Trail",
            directions:"Directions from Colorado Springs: ACCESS: 1. From Colorado Springs, take either 26th St. or Cheyenne Road to North Cheyenne Canyon Road to Gold Camp Road. About 1 mile past the locked gate at the intersection of North Cheyenne Canyon Road,Gold Camp Road andHigh Drive is the trailhead.",
            lat: 48.6746,
            lon: -113.60807,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11287106/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"6.3 miles",
            description:"The trail offers a number of activity options and is accessible year-round. Dogs are also able to use this trail but must be kept on leash. Main feature is a waterfall."
    },
    {
            city: "Crested Butte",
            name: "Trail 401",
            directions: "None Listed",
            difficulty: "Moderate",
            picture: "https://www.alltrails.com/api/alltrails/photos/18544251/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles: "16.3 mile loop",
            description: "Long climb but not too steep, followed by a long fast descent on singletrack through amazing wildflowers.  The trail tops out above treeline for some of the best views on any mountain biking trail. This trail can be ridden from Crested Butte, but most people start just above the town of Gothic.  Pedal to the top of Schofield Pass, and see the trailhead on your right.  The trail continues to climb for another 2 miles until it tops out just above treeline. Amazing views! Now it is downhill on singletrack through wildflowers all the way back to Gothic.",

    },
    {
            city: "Dinosaur",
            name: "Harpers Corner Trail",
            directions: "Directions from Dinosaur: Take Hwy. 40 East 2 miles from Dinosaur and turn north on Harper's Corner Rd at the monument headquarters. The trailhead is located at the end of the road.",
            lat: 40.5263526,
            lon:  -109.0165081,
            difficulty:"Easy",
            miles:"2.3 miles",
            picture:"https://www.alltrails.com/api/alltrails/photos/13734632/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description:"Fatures beautiful wild flowers and is good for all skill levels. The trail offers a number of activity options and is accessible year-round.",

    },
    {
            city: "Dinosaur",
            name: "Plug Hat Trail",
            directions: "Directions from Dinosaur: The trailhead is on Harper's Corner Road, about 4 miles from Dinosaur Monument Headquarters two miles east of Dinosaur, CO on WHY 40.",
            difficulty:"Easy",
            miles:"0.3 mile loop",
            picture:"https://www.alltrails.com/api/alltrails/photos/11121129/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description:"The trail offers a number of activity options and is accessible year-round.",

    },
    {
            city: "Drake",
            name: "Crosier Mountain",
            directions: "Directions from Loveland: Access #1: Travel west on Highway 34 approximately 15 miles to County Road 43, then travel north 8 miles to the site. Just west of the livery stables, there is a dirt road going south marked by a Crosier Mtn Trail sign. Park your vehicle off the highway and keep roadways clear. Access #2: Travel west on Highway 34 approximately 15 miles to County Road 43, then travel 6.5 miles to the trailhead. There is a large gravel cut on the south side of the road. A trail sign sits just up the hill from a gate.Access #3: Travel west on Highway 34 to County Road 43, then travel north 2.5 miles to the trailhead. Look for a small metal gate on the south side of the road. There is a small parking area near the gate.",
            lat: 40.4322,
            lon: 105.4247,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11545669/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"9.8 miles",
            description: "Features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is best used from March until September.",
 
    },
    {
            city: "Drake",
            name: "Storm Mountain Trail",
            directions: "None Listed",
            lat: 40.4855387,
            lon: -105.3858251,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/13550531/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"8.6 miles",
            description: "Great little surprise close to Loveland!  Magnificent and breathtaking views enroute and at the summit. Does not appear to be heavily traveled. Forest Service road (128 and 153) all the way to the summit. Somewhat strenuous as road/trail can be steep and rocky. Take plenty of water .",
 
    },
    {
            city: "Drake",
            name: "Sullivan Gulch Trail",
            directions: "On Rt. 34 just West of the Waltonia Road, on the North Side.",
            lat: 40.4149837,
            lon: -105.3652692,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/13345230/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"2.1 miles",
            description: "A short but steep hike up a heavily wooded canyon that abounds in solitude. A short hike that is good for training for some of the bigger trails that are in the local area.  There are several places near the summit that make a nice place to have a picnic. Good views of the Big Thompson Canyon and to the North is Signal Mtn. The Colorado weather makes this a hit or miss till spring. **Prime Mountain Lion country, so caution is advised.",
 
    },
    {
            city: "Elkdale",
            name: "Arapahoe Pass Trail Via Monarch",
            directions: "Directions from Granby: Follow Highway 40 west to Highway 34. Go north on Hwy 34 to Forest Road 125, on the south end of Lake Granby. Follow 125 east to the Monarch Lake Trailhead. Hike the Southside Trail around Monarch Lake to the Arapaho Pass Trail.",
            lat: 38.49719,
            lon: -106.326227,
            difficulty:"Hard",
            picture:"https://cdn-assets.alltrails.com/uploads/photo/image/11281347/extra_large_7621c54367614aaa221fb3ea979fb2a2.jpg",
            miles:"13.6 miles",
            description: "Arapahoe Pass Trail Via Monarch offers scenic views with a great forest setting. The trail is rated as difficult and primarily used for hiking, camping, and backpacking.",

    },
    {
            city: "Fort Collins",
            name: "Blue Sky",
            directions: "Devil's Backbone Trailhead - from Loveland: Take Highway 34 west of Loveland to just past mile marker #88 (2 miles west of the K-Mart). Turn right (north) onto Hidden Valley Drive just east of the old water tank. The trailhead is on your left. Soderberg Trailhead.",
            lat: 40.41182,
            lon: -105.15256,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11283429/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"16.1 miles",
            description: "The trail offers a number of activity options and is accessible year-round. Dogs are also able to use this trail. $6 parking fee.",
    },
    {
            city: "Fort Collins",
            name: "Foothills Trail: Maxwell Natural Area",
            directions:"The Foothills Trail can be reached from several trailheads managed by both the City of Fort Collins and Larimer County. Overland Trail Road provides access to the Reservoir Ridge Natural Area via Michaud Lane and the Maxwell Natural Area via County Road 42C. County Road 23 provides access to the Reservoir Ridge and also the many day use areas around Horsetooth Reservoir.",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/19207575/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"4.1 miles",
            description: "Located near Fort Collins, Colorado that offers the chance to see wildlife. The trail is good for all skill levels  offers a number of activity options. Dogs are also able to use this trail but must be kept on leash.",
    },
    {
            city: "Fort Collins",
            name: "Maxwel Falls Lower Trail",
            directions:"Directions from Evergreen for lower trail head: Take Highway 74 to the center of Evergreen. Turn right at the stoplight onto Highway 73. Go to Brook Forest Rd. and turn right. The lower trail head is encountered first on the left just past Columbine Road. To access the upper trail head go past the lower trail head to Black Mountain Road. On Black Mountain Road turn left and go 1.25 miles to the upper trail head.",
            lat: 40.55633,
            lon: -105.14103,
            description:"Maxwell Falls Lower Trail is a 4.2 mile heavily trafficked loop trail located near Evergreen, Colorado that features a waterfall and is rated as moderate. The trail is primarily used for hiking, trail running, camping, and horses and is best used from March until October. Dogs are also able to use this trail but must be kept on leash.",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11575042/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"4.2 mile loop"
    },
    {
            city: "Fruita",
            name: "Dinosaur Hill Trail",
            directions: "1.5 miles south of Fruita on Hwy 340, east side.",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/11571356/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.2 mile loop",
            description: "The trail is primarily used for hiking, walking, and nature trips and is accessible year-round. Dogs are also able to use this trail but must be kept on leash. You might even see a Dinosaur!",
     
    },
    {
            city: "Glenwood Springs",
            name: "Boy Scout Trail",
            directions: "The legal way to do this trek is, to ride up Red Canyon Road on your bike or a shuttle. To do this take Highway 82 South towards Aspen until you get to Buffalo Valley/Beau Jo's. Hang a left on Red Canyon Rd and go up almost 2 miles. This route is 2 miles. The preferred route is to take Doc Holliday's trail up through a small stretch of private, meeting up with the Boy Scout. To get to Doc's take a left on 13th off of Grand/82 and then left on Bennett. The trailhead is well marked. ",
            lat: 34.0416,
            lon: 116.1857,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11577911/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"5.4 mile Loop",
            description: "Features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is best used from March until November.",

    },
    {
            city: "Glenwood Springs",
            name: "Hanging Lake Trail",
            directions: "Directions from Eagle: Travel 23 miles west of Eagle on I-70 to the Grizzly exit on Glenwood Canyon. Turn around, get back on the eastbound lane of I-70 and head back to the Hanging Lake exit (there is no westbound exit). There is a new large developed rest area with toilets, drinking water, information and parking. The trail itself begins 1/4 mile east of the rest area on the left just before a bridge. There are picnic tables at the rest area and at the trailhead. It is important to note that dogs are not allowed on this trail because of its high use. There are no facilities at the top of the trail and because of the strenuous nature of the trail, make sure you bring drinking water.",
            lat: 39.6016497,
            lon: -107.1919967,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11745269/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"2.8 miles",
            description: "Hanging Lake is near Glenwood Springs, Colorado is a fascinating place to see, high in the mountains, at the end of a hike along Deadhorse Creek and through rocky canyons. Hanging Lake located near Glenwood Springs, Colorado. The trail is great for hiking and normally takes 2-4 hours. The trail is very steep with many large rocks/steps. A little work and you will find yourself at one of Colorado's most visited and beautiful short hikes!",

    },
    {
            city: "Glenwood Springs",
            name: "Jess Weaver Trail",
            directions: "From Rifle, go east on I-70 to No Name exit 119 (about 30 miles) Take the exit, turn left and continue .5 of a mile to the parking area and trailhead. The trail is also known as the No Name Trail",
            lat: 39.56706,
            lon: 107.29385,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11195794/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"5.4 miles",
            description: "Features a waterfall and is rated as moderate. The trail is primarily used for hiking and trail running and is best used from May until October. Dogs are also able to use this trail.",

    },
    {
            city: "Glenwood Springs",
            name: "Glenwood Caverns Trail",
            directions: "The cave is located at Glenwood Caverns Adventure Park in Glenwood Springs, CO",
            lat: 39.5535,
            lon: 107.3326,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11307300/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.8 miles",
            description: "King's Row Cave is a guided cave tour located in Glenwood Caverns Adventure Park. King's Row Cave is a .25 mile guided cave tour located in Glenwood Caverns Adventure Park. The trail is rated as moderate because of the 127 steps required to enter the lower rooms of the cave. The trail is primarily used for hiking.",

    },
    {
            city: "Glenwood Springs",
            name: "Grizzly Creek Trail",
            directions: "None Listed",
            lat: 40.6397222,
            lon: -106.4052778,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/19231032/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7.9 miles",
            description: "The trail offers a number of activity options and is best used from April until November. Dogs are also able to use this trail but must be kept on leash.",

    },
    {
            city: "Glenwood Springs",
            name: "Red Mountain Trail",
            directions: "exit Glenwood Springs and come in to town.Turn right on 8th street ,come to the next stop and turn right.Come to the next stop and turn left.Go about .25 of a mile and turn right.This is where the road tee's.Go about 100YRDS. and then you need to take a left.The road will curve to the left,so take the road another 100YRDDS and your there. parking is to the left.",
            lat: 39.54513,
            lon: -107.33447,
            description: "Red Mountain Trail is a 6.7 mile moderately trafficked out and back trail located near Glenwood Springs, Colorado that offers the chance to see wildlife and is rated as moderate. The trail offers a number of activity options and is accessible year-round. Dogs are also able to use this trail but must be kept on leash.",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/10339389/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"6.7 miles"       
    
    },
    {
            city: "Glenwood Springs",
            name: "Rio Grande Trail",
            directions: "Directions from Aspen: The trail can be accessed from multiple points. In Aspen is is normally access from the Mill Street bridge over the Roaring Fork River or from the Cemetery Lane/Slaughterhouse Bridge. To access the trail from Mill Street, go north from the corner of Mill and Main about 2 blocks to the Roaring Fork River. To access the trail from Cemetery Lane, travel west from Aspen 1/4 mile on Highway 82. Just west of the Castle Creek Bridge, turn right at the Cemetery Lane stoplight. Follow Cemetery Lane1 mile to Slaughterhouse Bridge. There is a parking area on the left. Both the paved and unpaved trails can be accessed from this point.",
            lat: 37.6769473,
            lon: -106.3014221,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/10574289/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"42.5 miles",
            description: "You have (at least) three trail options. You can start in Glenwood Springs and journey uphill to Aspen, then take the RFTA (Roaring Fork Transit Authority) bus back; you can bus to Aspen and ride downhill (net) back. No matter which way you choose to go, you will enjoy this world-class, high altitude trail. This trail, is great for family bonding trips by foot, horseback, bike, inline skate, Trikke, recumbent, tandem, or nordic skis. The trail is also wheelchair accessible and great for walking with your best friend, whether that friend is the two-legged or four-legged variety.",

    },
    {
            city: "Golden",
            name: "South Table Mtn. Trail",
            directions: "There are many access points to this trail system, but I haven't found any parking lots for the trail. The best access is from I-70 in the Belmar shopping area, Turn off on Denver West Blvd (this is located between Colfax 38th ave.) going north. There is a Marriott hotel on your left at this point. Take your next left at the light (on Denver west pkwy towards NREL) and park in one of the larger parking lots on your left. There's also access from the other 2 sides of South Table, behind Applewood golf course and next to Coors Brewing, but I cant give directions to theses trail heads.",
            lat: 39.75227,
            lon: -105.21023,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/19235371/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"9.2 miles",
            description: "The trail offers a number of activity options and is accessible year-round.",

    },
    {
            city: "Grandy",
            name: "Monarch Lake Loop Trail",
            directions: "Monarch Lake is in the Arapaho National Recreation Area (ANRA), six miles northwest of Granby on US Highway 34, nine miles east on County Road 6 (Forest Road 125, Arapaho Bay Road) at the southeast end of Lake Granby.",
            lat: 39.93446,
            lon: -105.683122,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/19231174/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"4.1 miles",
            description:"The views of the mountains and rivers are breath taking especially early in the season around late May, with moose and other wildlife sightings in the area.   The trail will take you along the edge of Monarch lake and into the woods were you will cross both Arapaho and Buchanan Creeks along with several runoff steams.  This area is quite lovely but keep in mind that as this is a fairly easy trail there maybe a lot of traffic.  The trail is made up of the Cascade Creek and Arapaho Pass Trails and its spurs, but all of the turns are well marked.  It is always advisable to have a trail map of the area with you.  If you are looking for fishing or a nice view to picnic the lake area and trail head are a great. Dogs are allowed on leash in the Arapaho National Forest, but check with the ranger station for any local restrictions.  Remember to check in at the trail head.  There are bathroom facilities as well at the trail head."
    },
    {
            city: "Green Mountain Falls",
            name: "Crystal Falls",
            directions:"None Listed",
            description: "Features a waterfall and is rated as difficult. The trail is primarily used for hiking and walking and is best used from April until October.",
            picture:"https://www.alltrails.com/api/alltrails/photos/17738663/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            difficulty:"Hard",
            miles:"7.5 miles"
    },
    {
            city: "Green Mountain Falls",
            name: "Thomas Trail",
            directions:"None Listed",
            description: "Features a waterfall and is rated as moderate. The trail offers a number of activity options and is accessible year-round. Dogs are also able to use this trail but must be kept on leash.",
            picture:"https://www.alltrails.com/api/alltrails/photos/19067873/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            difficulty:"Moderate",
            miles:"2.4 mile loop"
    },
    {
            city: "Green Mountain Falls",
            name: "Ute Pass Trail",
            directions:"None Listed",
            description: "Ute Pass Trail features beautiful wild flowers. The trail is good for all skill levels and primarily used for hiking, walking, birding, and mountain biking. Dogs are also able to use this trail but must be kept on leash.",
            picture:"https://www.alltrails.com/api/alltrails/photos/18688835/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            difficulty:"Easy",
            miles:"3.8 miles"
    },
    {       city: "Idaho Springs",
            name: "Mount Bierstadt",
            directions:"10 minutes South or Georgetown on Guanella pass",
            lat: 39.5827653,
            lon: -105.6686151,
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/11251912/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7.3 miles",
            description:"Mount Bierstadt Trail features a lake and is rated as difficult. The trail offers a number of activity options and is best used from May until September. Dogs are also able to use this trail but must be kept on leash. Start out early if you plan to do both peaks, especially if you aren't used to the altitude. Wear clothes that will keep you warn during the ascent up Mt. Bierstadt and that will be easy to shed once you reach the peak and sunshine. Also, be prepared for strong winds and colder temps on the way up Bierstadt. Leather gloves can be used for the crossing of the saw tooth."
    },
    {       city: "Idaho Springs",
            name: "St. Mary's Glacier",
            directions:"On I-70, take exit 238 and head north on County Road 275 for about nine miles. The trail head will be on the left side of the road and requires a $5.00 parking fee at the lot.",
            lat: 39.8301,
            lon: 105.6400,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/13298515/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.4 miles",
            description:"The trail offers a number of activity options and is best used from December until February. Dogs are also able to use this trail but must be kept on leash. $5 parking fee."
    },
    {
            city: "Littleton",
            name: "Meadowlark Plymouth Creek Trail",
            directions: "None Listed",
            miles:"6 mile loop",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11055515/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description: "Features a waterfall and is rated as moderate. The trail is primarily used for hiking, walking, birding, and mountain biking and is accessible year-round. Dogs are also able to use this trail but must be kept on leash."
    },
    {
            city: "Louisville",
            name: "Coal Creek Trail",
            directions: "There are two trailheads for this section. The east one is about 0.5 miles south of S. Boulder Rd and 120th St. It is also about 1 mile east of Hwy 287. The west trailhead parking is off Hwy 42, right next to the Loiusville cemetary.",
            lat: 39.9733,
            lon: -105.11498,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/10526870/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"8.6 miles",
            description: "Features beautiful wild flowers and is good for all skill levels. The trail offers a number of activity options and is accessible year-round. Dogs and horses are also able to use this trail.",

    },
    {       city: "Loveland",
            name: "Devil's Backbone",
            directions:"West of Loveland on Rt. 34",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/19110003/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"4.4 miles",
            description:"A 3.5 mi. extension to the Devils Backbone Interpretive Trail.   After a short but fairly steep up hill you will enter a rolling plateau that has some awesome views of the CO foothills with Longs Peak in the background. If you're quiet and observant you may see some deer along with other wildlife. For an area that is so close to civilization the quiet and solitude of this place is a nice respite.   The views of the Devils Backbone from the summit gives a different view to this geological wonder."
    },
    {       city: "Loveland",
            name: "Dome Mountain",
            directions:"None Listed",
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/10965377/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"11.1 miles",
            description:"Offers scenic views and is rated as difficult. The trail is primarily used for hiking and is best used from April until November."
    },
    {       city: "Loveland",
            name: "Pinewood Lake Trail",
            directions:"None Listed",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/11626466/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"5.5 mile loop",
            description:"Includes Besant Point Trail (2.6 miles) and Shoshone Trail (1.5 miles). Besant Point Trail includes two wheelchair-accessible segments at either end. Requires Larimer County vehicle permit."
    },
    
    {       city: "Loveland",
            name: "Sheep Mountain Trail",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11265738/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"9.1 miles",
            description:"Features beautiful wild flowers and is rated as moderate. The trail is primarily used for hiking, walking, nature trips, and birding and is best used from April until November."
    },
    {
            city: "Mancos",
            name: "Chicken Creek Trail",
            directions: "None Listed",
            lat: 37.4530511,
            lon: -108.2295249,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11537020/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"13.8 miles",
            description: "Features a lake and is rated as moderate. The trail offers a number of activity options and is best used from February until October.",

    },
    {
            city: "Mancos",
            name: "Gold Run Trail",
            directions: "Directions from Mancos, Colorado: Travel 1/4 mile north on Colorado State Hwy 184, then turn east on Forest Development Road #561 for about 19.0 miles to the Gold Run Trailhead facilities. Trail begins at the southeast end of the facilities (near the corrals).",
            lat: 37.5080515,
            lon: -108.1231325,
            difficulty:"Hard",
            picture:"https://s-media-cache-ak0.pinimg.com/736x/8e/26/55/8e26559b06496155a09c1340895c33f5.jpg",
            miles:"4.2 miles",
            description: "Features beautiful wild flowers and is rated as difficult. The trail offers a number of activity options and is best used from May until November. * No Atv use.",

    },
    {
            city: "Mancos",
            name: "Sharkstooth Path Trail",
            directions: "None Listed",
            lat: 37.4564,
            lon: 108.1344,
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/11137216/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"2.0 miles",
            description: "To access the trail head you must drive 4-5 miles on a moderately difficult 4-wheel drive road. Street vehicles likely cannot make it. Please only attempt this road in dry weather. The trail offers a number of activity options and is best used from March until September.",
    },
    {       city: "Montrose",
            name: "Gunnison Route Trail",
            directions:"None Listed",
            lat: 38.544537,
            lon: -106.928354,
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/11660176/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"2.2 miles",
            description:" Features a river and is only recommended for very experienced adventurers. The trail offers a number of activity options and is best used from April until September."
    },
    {       city: "Montrose",
            name: "Oak Flat Trail",
            directions:"None Listed",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/19267187/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.3 mile loop",
            description:"Offers the chance to see wildlife and is rated as moderate. The trail is primarily used for hiking, walking, nature trips, and birding and is best used from March until October."
    },
    {       city: "Montrose",
            name: "Painted Wall View Trail",
            directions:"None Listed",
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/19254888/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"0.3 miles",
            description:"Features beautiful wild flowers and is good for all skill levels. The trail offers a number of activity options and is best used from March until October."
    },
    {
            city: "Montrose",
            name: "Rim Rock Nature Trail",
            directions: "From Montrose, follow signs for Black Canyon of the Gunnison National Park.  The trail head is located next to the campground, a couple miles inside the park entrance.",
            description: "Rim Rock Nature Trail is a 1.6 mile lightly trafficked out and back trail located near Montrose, Colorado that features beautiful wild flowers and is rated as moderate. The trail is primarily used for hiking, walking, nature trips, and birding and is best used from March until October.",
            difficulty:"Moderate",
            picture:"https://www.alltrails.com/api/alltrails/photos/19244536/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.6 miles"  
    },
    {       city: "Montrose",
            name: "Warner Point Nature Trail",
            directions:"Black Canyon of the Gunnison National Park is located approximately 250 miles southwest of Denver. South Rim (to access the Warner Point Nature trail): 15 miles east of Montrose, via U.S. Highway 50 and CO Highway 347. North Rim: 11 miles south of Crawford, via CO Highway 92 and North Rim Road (unpaved). There is no bridge between the north and south rims of the canyon. Allow two to three hours to drive from one side to the other.",
            difficulty:"Easy",
            lat: 38.5625,
            lon: 107.7420,
            picture:"https://www.alltrails.com/api/alltrails/photos/10724226/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"1.5 miles",
            description:"Warner Point Nature Trail offers a great taste of the Black Canyon of the Gunnison at the end of South Rim Road.   Scenic 1.5 mile RT hike to a great view of the canyon and river below."
    },
    {
            city: "Pine",
            name: "Buck Gulch",
            directions: "o access the Buffalo Creek Recreation area from Denver, travel Highway 285 South (west) to Pine Junction. Turn south on Highway 126 and continue 13.5 miles to Forest Service road 550. Turn right, heading west and travel 7.5 miles, keeping right at each Y to Forest Service road 553. Turn right and the trailhead is 2.5 miles ahead. To access the Buffalo Creek Recreation area from Bailey, travel Park County road 68 (Wellington Lake Road) to the first Y.  Turn left, heading east and travel 2 miles to Forest Service road 553. Turn left and the trailhead is 2.5 miles ahead.",
            lat: 39.40722,
            lon: -105.34639,
            difficulty: "Moderate",
            miles: "11.7 mile loop",
            picture: "https://www.alltrails.com/api/alltrails/photos/10788705/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description: "Features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is best used from March until October. Open year around but snow can be  a limiting factor.",
    
    },
    {       city: "Pine",
            name: "Rolling Creek Trail",
            directions:"None Listed",
            difficulty:"Hard",
            picture:"https://www.alltrails.com/api/alltrails/photos/13650881/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7.1 miles",
            description:"Features a river and is rated as difficult. The trail offers a number of activity options and is best used from March until October."
    },
    {
            city: "Redlands",
            name: "Liberty Cap",
            directions:"None Listed",
            difficulty:"Moderate",
            miles:"13.4 miles",
            picture:"https://www.alltrails.com/api/alltrails/photos/14807846/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description:"From the Wildwood Trailhead on the East side of Colorado National Monument  climb the mesa via switchbacks that climb the wall quickly. Beautiful trail offering an impressive vista of Colorado National Monument and Independence Rock in particular. Visitors can use the Wildwood Trailhead on the East side of the park that then connects with Liberty Cap Trail. This access point requires some steep inclines, but once you've made it to the top of the mesa you're rewarded with beautiful views."

    },
    {
            city: "Sterling",
            name: "South Shoreline Trail",
            directions: "From I-76, take exit #125 (Sterling) and turn west on Hwy 6 (eastbound traffic from Denver, turn left off the exit ramp - westbound traffic from Julesburg/Nebraska, turn right the off exit ramp). Follow Hwy 6 west for 2 miles over the bridge into downtown Sterling. The road becomes Chestnut St - continue straight. After 3 blocks, the road jogs left and becomes Platte St. Continue on Platte St for 2 blocks to the four-way stop at N. 3rd Ave. Turn right at the stop sign and go 4 blocks to Broadway. Turn left at the traffic light and go 4 blocks to N. 7th Ave. Turn right onto N. 7th Ave and follow the directions below.",
            lat: 40.765472,
            lon: -103.26838,
            difficulty:"Easy",
            picture:"https://www.alltrails.com/api/alltrails/photos/19052093/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles:"7 miles",
            description: "South Shoreline Trail features a lake and is good for all skill levels. The trail offers a number of activity options and is best used from March until October."
    },
    {       
            city: "Walsenburg",
            name: "Hogback Nature Trail",
            difficulty: "Easy",
            directions: "Three miles west of Walsenburg Colorado on U.S. Highway 160",
            miles: "1.5 mile loop",
            picture: "https://www.alltrails.com/api/alltrails/photos/10791612/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            description: "The trail winds through sandstone formations and then climbs up the rocky Hogback Ridge that forms the park's northern boundary. As the trail follows the top of the ridge, majestic views of the Spanish Peaks, Sangre de Cristo and Wet Mountain Ranges can be enjoyed. Along the two-mile trail, marker posts have been installed to accompany a self-guided brochure containing information about the area's plant and animal life and its history. The brochures are complimentary and  are available at the trailhead. . Bicycles are prohibited on this designated nature trail."
    },
    {
            city: "Walsenburg",
            name: "Highway of Legends",
            difficulty: "Easy",
            picture: "https://www.alltrails.com/api/alltrails/photos/11443475/image?size=extra_large&api_key=3p0t5s6b5g4g0e8k3c1j3w7y5c3m4t8i",
            miles: "36.6 miles",
            directions: "None Listed",
            description: "Offers scenic views and is good for all skill levels. The trail is primarily used for nature trips and scenic driving and is accessible year-round.",

    },
    // {       city: "",
    //         name: "",
    //         directions:"",
    //         lat: ,
    //         lon: ,
    //         difficulty:"",
    //         picture:"",
    //         miles:"",
    //         description:""
    // },

]